steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        npm run build

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/ai-virtual-staging/ai-virtual-staging:$COMMIT_SHA',
        '.'
      ]

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/ai-virtual-staging/ai-virtual-staging:$COMMIT_SHA'
      ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'ai-virtual-staging-new',
        '--image',
        'us-central1-docker.pkg.dev/$PROJECT_ID/ai-virtual-staging/ai-virtual-staging:$COMMIT_SHA',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/ai-virtual-staging/ai-virtual-staging:$COMMIT_SHA'
